export const RPCities: string[] = [
  "Mainz",
  "Ludwigshafen am Rhein",
  "Koblenz",
  "Trier",
  "Kaiserslautern",
  "Worms",
  "Neuwied",
  "Neustadt an der Weinstraße",
  "Speyer",
  "Bad Kreuznach",
  "Frankenthal (Pflaz)",
  "Landau in der Pfalz",
  "Primasens",
  "Zweibrücken",
  "Andernach",
  "Idar-Oberstein",
  "Bad Neuenahr-Ahrweiler",
  "Bingen am Rhein",
  "Ingelheim am Rhein",
  "Germersheim",
  "Schifferstadt",
  "Mayen",
  "Wittlich",
  "Bad Dürkheim",
  "Alzey",
  "Konz",
  "Wörth am Rheim",
  "Lahnstein",
  "Sinzig",
  "Bendorf",
];
